execute pathogen#infect('bundle/{}')
filetype plugin indent on

syntax enable
set background=dark
let g:solarized_termcolors=256
colorscheme solarized


set colorcolumn=90

set number
set hidden
set history=100
set hlsearch

set nowrap
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set autoindent

set showmatch

autocmd BufWritePre * :%s/\s\+$//e

let mapleader=" "
map <leader>s :source ~/.vimrc<CR>

map <D-A-RIGHT> <C-w>l
map <D-A-LEFT> <C-w>h
map <D-A-DOWN> <C-w><C-w>
map <D-A-UP> <C-w>W

nnoremap <silent> <Esc> :nohlsearch<Bar>:echo<CR>
nnoremap <Leader><Leader> :e#<CR>


