execute pathogen#infect('bundle/{}')
filetype plugin indent on

syntax enable
set background=dark
let g:solarized_termcolors=256
colorscheme solarized

set colorcolumn=90


set number
set hidden
set history=100
set hlsearch

set nowrap
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set autoindent

set showmatch
set noshowmode
set laststatus=2

autocmd BufWritePre * :%s/\s\+$//e

let mapleader=" "
map <leader>s :source ~/.vimrc<CR>

nnoremap <Leader><Leader> :e#<CR>

"NerdTree Configuration
let NERDTreeMapActivateNode='<right>'
let NERDTreeShowHidden=1
let NERDTreeIgnore=['\.DS_Store', '\~$', '\,swp']
nmap <leader>n :NERDTreeToggle<CR>
nmap <leader>j :NERDTreeFind<CR>

"gitGutter Configuration
set signcolumn=yes
