#!/usr/bin/env bash

# Update dotfiles
dfu() {
    (
        cd ~/.dotfiles && git pull --ff-only && ./install -q
    )
}

# Create a directory and cd into it
take() {
    mkdir -p "${1}" && cd "${1}"
}

# Jump to directory containing file
jump() {
    cd "$(dirname ${1})"
}

# View markdown files from terminal
rmd () {
  pandoc $1 | lynx -stdin
}

# Usage: extract <file>
# Description: extracts archived files / mounts disk images
# Note: .dmg/hdiutil is macOS-specific.
#
# credit: http://nparikh.org/notes/zshrc.txt
extract () {
    if [ -f $1 ]; then
        case $1 in
            *.tar.bz2)  tar -jxvf $1                        ;;
            *.tar.gz)   tar -zxvf $1                        ;;
            *.bz2)      bunzip2 $1                          ;;
            *.dmg)      hdiutil mount $1                    ;;
            *.gz)       gunzip $1                           ;;
            *.tar)      tar -xvf $1                         ;;
            *.tbz2)     tar -jxvf $1                        ;;
            *.tgz)      tar -zxvf $1                        ;;
            *.zip)      unzip $1                            ;;
            *.ZIP)      unzip $1                            ;;
            *.pax)      cat $1 | pax -r                     ;;
            *.pax.Z)    uncompress $1 --stdout | pax -r     ;;
            *.rar)      unrar x $1                          ;;
            *.Z)        uncompress $1                       ;;
            *)          echo "'$1' cannot be extracted/mounted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

# `o` with no arguments opens the current directory, otherwise opens the given
# location
function o() {
	if [ $# -eq 0 ]; then
		open .;
	else
		open "$@";
	fi;
}

# Use Git’s colored diff when available
hash git &>/dev/null;
if [ $? -eq 0 ]; then
	function diff() {
		git diff --no-index --color-words "$@";
	}
fi;

# Start a PHP server from a directory, optionally specifying the port
# (Requires PHP 5.4.0+.)
function phpserver() {
	local port="${1:-4000}";
	local ip=$(ipconfig getifaddr en1);
	sleep 1 && open "http://${ip}:${port}/" &
	php -S "${ip}:${port}";
}

# `tre` is a shorthand for `tree` with hidden files and color enabled, ignoring
# the `.git` directory, listing directories first. The output gets piped into
# `less` with options to preserve color and line numbers, unless the output is
# small enough for one screen.
function tre() {
	tree -aC -I '.git|node_modules|bower_components' --dirsfirst "$@" | less -FRNX;
}

function git-undo() { 
    git reset --soft HEAD^
}

function gclonecd() { 
    git_dir="$(basename "$1" .git)"
    git_dir_resolved=${2:-$git_dir}
    git clone "$@" && cd "$git_dir_resolved";
}

function killport() {
    echo "Killing process on port: $1"
    fuser -n tcp -k $1;
}

function whoinport() {
    lsof -nP -i4TCP:$1 | grep LISTEN
}

#Bash function to change directories and list contents
#cd() {
    #builtin cd $@
    #ls -lh
#}
# OS Detection
function is_osx(){
    [[ "$OSTYPE" =~ ^darwin ]] || return 1
}

function is_ubuntu(){
    [[ "$(cat /etc/issue 2> /dev/null)" =~ Ubuntu ]] ||  return 1
}

function is_ubuntu_desktop(){
    dpkg -l ubuntu-desktop >/dev/null 2>&1 || return 1
}

function get_os(){
    for os in osx ubuntu ubuntu_desktop; do
        is_$os; [[ $? == ${1:0} ]] && echo $os
    done
}

# Remove an entry from PATH
# Based on http://stackoverflow.com/a/2108540/142339
function path_remove(){
    local arg path
    path=":$PATH:"
    for arg in "$@"; do path="${path//:$arg:/:}"; done
    path="${path%:}"
    path="${path#:}"
    echo "$path"
}

# apparix (sudo apt-get install apparux // brew install -v apparix)
function to () {
   if test "$2"; then
     cd "$(apparix "$1" "$2" || echo .)";
   else
     cd "$(apparix "$1" || echo .)";
   fi
   pwd
}
function bm () {
   if test "$2"; then
     apparix --add-mark "$1" "$2";
   elif test "$1"; then
     apparix --add-mark "$1";
   else
     apparix --add-mark;
   fi
}
function portal () {
   if test "$1"; then
     apparix --add-portal "$1";
   else
     apparix --add-portal;
   fi
}
# function to generate list of completions from .apparixrc
function _apparix_aliases (){
  cur=$2
  dir=$3
  COMPREPLY=()
  if [ "$1" == "$3" ]
  then
    COMPREPLY=( $( cat $HOME/.apparix{rc,expand} | \
                   grep "j,.*$cur.*," | cut -f2 -d, ) )
  else
    dir=`apparix -favour rOl $dir 2>/dev/null` || return 0
    eval_compreply="COMPREPLY=( $(
        cd "$dir"
        \ls -d *$cur* | while read r
        do
            [[ -d "$r" ]] &&
            [[ $r == *$cur* ]] &&
                echo \"${r// /\\ }\"
        done
        ) )"
    eval $eval_compreply
  fi
  return 0
}
# command to register the above to expand when the 'to' command's args are
# being expanded
complete -F _apparix_aliases to

