# ~/.bash_aliases - alias productivos y seguros

alias ll='ls -lah'
alias la='ls -A'
alias l='ls'

# Modernos y seguros
alias ls="exa -lah"
alias cat="bat --paging=never"
alias grep="rg --color=auto"
alias rm="rm -i"
alias cp="cp -i"
alias mv="mv -i"
alias vim="nvim"

# Atajos útiles
alias cls="clear"
alias reload="source ~/.bashrc"
alias path='echo -e ${PATH//:/\\n}'

